# Generated by Django 2.2 on 2019-08-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'Orders Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
    ]
